<a href="https://colab.research.google.com/github/madhumithamadasamy/DataAnalytics-Using-Python-Project/blob/main/Numpy_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array([90,85,78,92])

print(marks)

[90 85 78 92]


In [ ]:

import numpy as np

students=np.array([
    [90,85],
    [78,92],
    [88,96]
])

print(students)

[[90 85]
 [78 92]
 [88 96]]


In [ ]:
import numpy as np
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
