<a href="https://colab.research.google.com/github/madhumithamadasamy/DataAnalytics-Using-Python-Project/blob/main/Reshape_and_transpose_day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,0])

new_arr = arr.reshape(5,2)

print(new_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [ ]:
# find mean value

import numpy as np
marks = np.array([70,80,90,60])
average = np.mean(marks)
print(average)

75.0


In [ ]:
# find median value

import numpy as np
salary = np.array([10000,20000,30000,40000,50000])
med = np.median(salary)
print(med)

30000.0


In [ ]:
import numpy as np
marks = np.array([70,80,90,60])
average = np.median(marks)
print(average)

75.0
